In [68]:
from google.colab import files
uploaded = files.upload()

Saving avocado2.csv to avocado2.csv


In [35]:
import pandas as pd
df = pd.read_csv("avocado.csv")
print("ID : D19IT149")
df.head()

ID : D19IT149


Unnamed: 0        Date  AveragePrice  ...          type  year  region
0           0  27 12 2015          1.33  ...  conventional  2015  Albany
1           1  20 12 2015          1.35  ...  conventional  2015  Albany
2           2  13 12 2015          0.93  ...  conventional  2015  Albany
3           3  06 12 2015          1.08  ...  conventional  2015  Albany
4           4  29 11 2015          1.28  ...  conventional  2015  Albany

[5 rows x 14 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18249 entries, 0 to 18248
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    18249 non-null  int64  
 1   Date          18249 non-null  object 
 2   AveragePrice  18249 non-null  float64
 3   Total Volume  18249 non-null  float64
 4   4046          18249 non-null  float64
 5   4225          18249 non-null  float64
 6   4770          18249 non-null  float64
 7   Total Bags    18249 non-null  float64
 8   Small Bags    18249 non-null  float64
 9   Large Bags    18249 non-null  float64
 10  XLarge Bags   18249 non-null  float64
 11  type          18249 non-null  object 
 12  year          18249 non-null  int64  
 13  region        18249 non-null  object 
dtypes: float64(9), int64(2), object(3)
memory usage: 1.9+ MB


In [35]:
from sklearn.preprocessing import Normalizer
import pandas
import numpy
dataframe = pandas.read_csv("avocado.csv", usecols=['AveragePrice','Total Volume','Total Bags','XLarge Bags','year','region'])
array = dataframe.values
X = array[:,0:5]
Y = array[:,5]
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)
numpy.set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[2.051e-05 9.905e-01 1.341e-01 0.000e+00 3.107e-02]
 [2.422e-05 9.847e-01 1.706e-01 0.000e+00 3.616e-02]
 [7.847e-06 9.975e-01 6.873e-02 0.000e+00 1.700e-02]
 [1.363e-05 9.970e-01 7.334e-02 0.000e+00 2.543e-02]
 [2.488e-05 9.920e-01 1.202e-01 0.000e+00 3.916e-02]]


In [5]:
from sklearn.preprocessing import StandardScaler
import pandas
import numpy
dataframe = pandas.read_csv("avocado.csv", usecols=['AveragePrice','Total Volume','Total Bags','XLarge Bags','year','region'])
array = dataframe.values
X = array[:,0:5]
Y = array[:,5]
scaler = StandardScaler().fit(X)
normalizedX = scaler.transform(X)
numpy.set_printoptions(precision=3)
print(normalizedX[0:5,:])

[[-0.189 -0.228 -0.234 -0.176 -1.221]
 [-0.139 -0.23  -0.233 -0.176 -1.221]
 [-1.182 -0.212 -0.235 -0.176 -1.221]
 [-0.81  -0.223 -0.237 -0.176 -1.221]
 [-0.313 -0.232 -0.237 -0.176 -1.221]]


In [30]:
(df== 0).sum()

Unnamed: 0        432
Date                0
AveragePrice        0
Total Volume        0
4046              242
4225               61
4770             5497
Total Bags         15
Small Bags        159
Large Bags       2370
XLarge Bags     12048
type                0
year                0
region              0
dtype: int64

In [48]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=0, strategy='mean')
agent_col = imputer.fit_transform(df['XLarge Bags'].values.reshape(-1,1))
pd.DataFrame(agent_col).isnull().sum()

0    0
dtype: int64

In [49]:
print(df['type'].unique())
print(df['region'].unique())

['conventional' 'organic']
['Albany' 'Atlanta' 'BaltimoreWashington' 'Boise' 'Boston'
 'BuffaloRochester' 'California' 'Charlotte' 'Chicago' 'CincinnatiDayton'
 'Columbus' 'DallasFtWorth' 'Denver' 'Detroit' 'GrandRapids' 'GreatLakes'
 'HarrisburgScranton' 'HartfordSpringfield' 'Houston' 'Indianapolis'
 'Jacksonville' 'LasVegas' 'LosAngeles' 'Louisville' 'MiamiFtLauderdale'
 'Midsouth' 'Nashville' 'NewOrleansMobile' 'NewYork' 'Northeast'
 'NorthernNewEngland' 'Orlando' 'Philadelphia' 'PhoenixTucson'
 'Pittsburgh' 'Plains' 'Portland' 'RaleighGreensboro' 'RichmondNorfolk'
 'Roanoke' 'Sacramento' 'SanDiego' 'SanFrancisco' 'Seattle'
 'SouthCarolina' 'SouthCentral' 'Southeast' 'Spokane' 'StLouis' 'Syracuse'
 'Tampa' 'TotalUS' 'West' 'WestTexNewMexico']


In [55]:
df['type'].value_counts()

conventional    9126
organic         9123
Name: type, dtype: int64

In [56]:
df['region'].value_counts()

Indianapolis           338
Detroit                338
LasVegas               338
Nashville              338
RichmondNorfolk        338
HarrisburgScranton     338
Midsouth               338
NewYork                338
BaltimoreWashington    338
SanDiego               338
SouthCentral           338
Chicago                338
Charlotte              338
Pittsburgh             338
Jacksonville           338
Denver                 338
RaleighGreensboro      338
SanFrancisco           338
Portland               338
DallasFtWorth          338
Tampa                  338
LosAngeles             338
NewOrleansMobile       338
Plains                 338
BuffaloRochester       338
Louisville             338
Roanoke                338
SouthCarolina          338
StLouis                338
Northeast              338
California             338
NorthernNewEngland     338
Southeast              338
Albany                 338
Columbus               338
PhoenixTucson          338
Houston                338
B

In [57]:
one_hot_encoded_data = pd.get_dummies(df, columns = ['type', 'region'])
print(one_hot_encoded_data)

       Unnamed: 0        Date  ...  region_West  region_WestTexNewMexico
0               0  27 12 2015  ...            0                        0
1               1  20 12 2015  ...            0                        0
2               2  13 12 2015  ...            0                        0
3               3  06 12 2015  ...            0                        0
4               4  29 11 2015  ...            0                        0
...           ...         ...  ...          ...                      ...
18244           7  04 02 2018  ...            0                        1
18245           8  28 01 2018  ...            0                        1
18246           9  21 01 2018  ...            0                        1
18247          10  14 01 2018  ...            0                        1
18248          11  07 01 2018  ...            0                        1

[18249 rows x 68 columns]


In [69]:
df2 = pd.read_csv("avocado2.csv")
print("ID : D19IT149")
df2.head()

ID : D19IT149


Unnamed: 0  AveragePrice  Total Volume  ...  Large Bags  XLarge Bags  year
0           0          1.33      64236.62  ...       93.25          0.0  2015
1           1          1.35      54876.98  ...       97.49          0.0  2015
2           2          0.93     118220.22  ...      103.14          0.0  2015
3           3          1.08      78992.15  ...      133.76          0.0  2015
4           4          1.28      51039.60  ...      197.69          0.0  2015

[5 rows x 11 columns]

In [73]:
from sklearn.preprocessing import KBinsDiscretizer
trans = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='kmeans')
new_data = trans.fit_transform(df2)
pd.DataFrame(new_data, columns=df2.columns)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:184: ConvergenceWarning: Number of distinct clusters (9) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  centers = km.fit(column[:, None]).cluster_centers_[:, 0]
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 8 are removed. Consider decreasing the number of bins.
  'decreasing the number of bins.' % jj)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:184: ConvergenceWarning: Number of distinct clusters (4) found smaller than n_clusters (10). Possibly due to duplicate points in X.
  centers = km.fit(column[:, None]).cluster_centers_[:, 0]
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_discretization.py:197: UserWarning: Bins whose width are too small (i.e., <= 1e-8) in feature 10 are removed. Consider decreasing the number of 

Unnamed: 0  AveragePrice  Total Volume  ...  Large Bags  XLarge Bags  year
0             0.0           3.0           0.0  ...         0.0          0.0   0.0
1             0.0           3.0           0.0  ...         0.0          0.0   0.0
2             0.0           1.0           0.0  ...         0.0          0.0   0.0
3             0.0           1.0           0.0  ...         0.0          0.0   0.0
4             0.0           2.0           0.0  ...         0.0          0.0   0.0
...           ...           ...           ...  ...         ...          ...   ...
18244         1.0           5.0           0.0  ...         0.0          0.0   3.0
18245         1.0           5.0           0.0  ...         0.0          0.0   3.0
18246         1.0           6.0           0.0  ...         0.0          0.0   3.0
18247         1.0           6.0           0.0  ...         0.0          0.0   3.0
18248         2.0           5.0           0.0  ...         0.0          0.0   3.0

[18249 rows x 11 columns]